# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PPPWight.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtCore.QObject):
    infoEmit = QtCore.pyqtSignal(str,str)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1114, 715)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./source/icon/dingweixian.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setMaximumSize(QtCore.QSize(350, 400))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_elliPara = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_elliPara.setObjectName("comboBox_elliPara")
        self.comboBox_elliPara.addItem("")
        self.comboBox_elliPara.addItem("")
        self.comboBox_elliPara.addItem("")
        self.comboBox_elliPara.addItem("")
        self.comboBox_elliPara.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_elliPara)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_PP = QtWidgets.QPushButton(self.groupBox_3)
        self.button_PP.setObjectName("button_PP")
        self.horizontalLayout_4.addWidget(self.button_PP)
        self.button_mapLacation = QtWidgets.QPushButton(self.groupBox_3)
        self.button_mapLacation.setObjectName("button_mapLacation")
        self.horizontalLayout_4.addWidget(self.button_mapLacation)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setText("")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setChecked(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.status_slider = QtWidgets.QSlider(self.groupBox_3)
        self.status_slider.setAutoFillBackground(False)
        self.status_slider.setStyleSheet("color: rgb(0, 170, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"border-color: rgb(0, 255, 255);")
        self.status_slider.setMaximum(1)
        self.status_slider.setTracking(True)
        self.status_slider.setOrientation(QtCore.Qt.Horizontal)
        self.status_slider.setInvertedAppearance(False)
        self.status_slider.setInvertedControls(False)
        self.status_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.status_slider.setTickInterval(0)
        self.status_slider.setObjectName("status_slider")
        self.horizontalLayout_5.addWidget(self.status_slider)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./source/icon/icon_educa.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_6.addWidget(self.groupBox)

        self.retranslateUi(Form)
        self.button_PP.clicked.connect(self.actionGetPosition)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "精密单点定位(PPP)"))
        self.label.setText(_translate("Form", "参考椭球："))
        self.comboBox_elliPara.setItemText(0, _translate("Form", "WGS84"))
        self.comboBox_elliPara.setItemText(1, _translate("Form", "CGCS2000"))
        self.comboBox_elliPara.setItemText(2, _translate("Form", "克拉索夫斯基椭球"))
        self.comboBox_elliPara.setItemText(3, _translate("Form", "1975国际参考椭球"))
        self.comboBox_elliPara.setItemText(4, _translate("Form", "自定义椭球"))
        self.button_PP.setText(_translate("Form", "标准单点定位"))
        self.button_mapLacation.setText(_translate("Form", "查看地图点位"))
        self.groupBox.setTitle(_translate("Form", "数据"))

    def actionGetPosition(self):
        self.sendTopInfo("J","信号已连接")

    def sendTopInfo(self,type,strInfo):
        if type == "J":
            self.textEdit.append(strInfo)
