# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gravityFieldApplicationWight.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtCore.QObject):
    infoEmit = QtCore.pyqtSignal(str, str)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1175, 689)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./source/icon/bance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMaximumSize(QtCore.QSize(310, 200))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout_2.addWidget(self.commandLinkButton)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./source/icon/hore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.tab_2)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.verticalLayout_3.addWidget(self.commandLinkButton_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./source/icon/sang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.commandLinkButton.clicked.connect(self.actionButtonMeasureDataCacu)
        self.commandLinkButton_2.clicked.connect(self.actionModelCacu)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.commandLinkButton.setText(_translate("Form", "采用测量数据解算\n"
                                                          "重力异常\n"
                                                          "数据组成形式:\n"
                                                          " [ID,Lon,Lat,H,g]\n"
                                                          ""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "测量数据解算"))
        self.commandLinkButton_2.setText(_translate("Form", "采用已有重力场模型\n"
                                                            "解算重力异常"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "重力场模型解算"))
        self.groupBox_2.setTitle(_translate("Form", "输出"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "经度/°"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "纬度/°"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "测量点高程/H"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "测量点重力值/mGal"))

    def actionButtonMeasureDataCacu(self):
        pass

    def actionModelCacu(self):
        pass

    def killThread(self):
        pass

    def sendTopInfo(self, type, strInfo):
        self.infoEmit.emit(type, strInfo)
