# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inversionGravityFieldWight.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database.database import Database
from window.geodeticSurvey import actionInversionGravityFieldThread


class Ui_Form(QtCore.QObject):
    infoEmit = QtCore.pyqtSignal(str, str)
    filePath = None
    lineLenght = 0
    nowN = 0
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1167, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../source/icon/bance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 350))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(5000)
        self.spinBox.setProperty("value", 180)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_5.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setCheckable(True)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../source/icon/earth.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar_2.setProperty("value", 20)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setObjectName("progressBar_2")
        self.horizontalLayout_2.addWidget(self.progressBar_2)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        self.radioButton.clicked.connect(self.actionRadioButton)
        self.radioButton_2.clicked.connect(self.actionRadioButton)
        self.radioButton_3.clicked.connect(self.actionRadioButton)
        self.radioButton_4.clicked.connect(self.actionRadioButton)
        self.radioButton_5.clicked.connect(self.actionRadioButton)

        self.pushButton.clicked.connect(self.startInversionGravityFiled)
        self.pushButton_2.clicked.connect(self.textEdit.clear)

        self.cacuThread = actionInversionGravityFieldThread.ActionInversionGravityField()
        self.cacuThread.infoEmit.connect(self.sendTopInfo)
        self.cacuThread.overEmit.connect(self.killCacuThread)
        self.cacuThread.processEmit.connect(self.setProcess)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "操作"))
        self.label_2.setText(_translate("Form", "反演最大阶："))
        self.checkBox.setText(_translate("Form", "保存模型到工作空间"))
        self.radioButton.setText(_translate("Form", "区域重力异常数据反演"))
        self.radioButton_2.setText(_translate("Form", "全球重力异常数据反演"))
        self.radioButton_3.setText(_translate("Form", "重力卫星轨道和梯度数据反演"))
        self.radioButton_4.setText(_translate("Form", "GRACE卫星等低轨卫星跟踪数据反演"))
        self.radioButton_5.setText(_translate("Form", "其他反演手段"))
        self.pushButton.setText(_translate("Form", "反演重力场"))
        self.pushButton_2.setText(_translate("Form", "清空"))
        self.groupBox_2.setTitle(_translate("Form", "信息"))

    def actionRadioButton(self):
        if self.radioButton_2.isChecked():
            fileName, type = QtWidgets.QFileDialog.getOpenFileName(self.parent(), "导入全球重力异常数据", Database.workspace,
                                                                   "All File(*);;Txt(.txt)")
            if fileName != "":
                self.filePath = fileName
                self.radioButton_2.setChecked(True)

        elif self.radioButton.isChecked():
            self.sendTopInfo("T", "当前功能尚未开发！")
            self.radioButton.setChecked(False)
        elif self.radioButton_3.isChecked():
            self.radioButton_3.setChecked(False)
            self.sendTopInfo("T", "当前功能尚未开发！")
        elif self.radioButton_4.isChecked():
            self.radioButton_4.setChecked(False)
            self.sendTopInfo("T", "当前功能尚未开发！")
        else:
            self.radioButton_5.setChecked(False)
            self.sendTopInfo("T", "当前功能尚未开发！")

    def sendTopInfo(self, type, strInfo):
        if type == "G":
            self.textEdit.append(strInfo)
            if self.lineLenght > 100:
                self.textEdit.clear()
        else:
            self.infoEmit.emit(type, strInfo)

    def setProcess(self, m, n):
        # 打开窗口
        self.progressBar_2.setMaximum(n)
        self.progressBar_2.setValue(m)
        self.progressBar.setMaximum(180)
        if self.nowN != n:
            self.progressBar.setValue(n)
            self.nowN = n



    def startInversionGravityFiled(self):
        if self.filePath is None:
            self.sendTopInfo("T", "未选择反演方法并导入数据")
        else:
            # 判断选择的方法
            if self.radioButton.isChecked():
                controlCode = 100
            elif self.radioButton_2.isChecked():
                controlCode = 101
            elif self.radioButton_3.isChecked():
                controlCode = 102
            elif self.radioButton_4.isChecked():
                controlCode = 103
            else:
                controlCode = 104
            # 设置线程参数
            paraDict = {"code": controlCode, "filePath": self.filePath,"autoSave":self.checkBox.isChecked(),"N":int(self.spinBox.text())}
            self.cacuThread.setPara(paraDict)
            self.progressBar.setMaximum(paraDict["N"])
            # 开启线程
            self.cacuThread.start()
            self.sendTopInfo("I", "子线程已启动，准备进行重力场模型反演...")

    def killCacuThread(self):
        self.cacuThread.killThread()
        self.sendTopInfo("I", "已关闭重力场模型反演线程")
