# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'threeDimensionalReconstructionWight.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets

from window.geodeticSurvey import callExModuleThread


class Ui_Form(QtCore.QObject):
    infoEmit = QtCore.pyqtSignal(str, str)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1044, 624)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        self.callModule = callExModuleThread.CallExModule()
        self.callModule.infoEmit.connect(self.showInfo)
        self.pushButton_3.clicked.connect(self.actionCallVisualSFM)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "操作"))
        self.radioButton.setText(_translate("Form", "相机参数标定"))
        self.pushButton.setText(_translate("Form", "相机参数标定"))
        self.pushButton_2.setText(_translate("Form", "导入多方位影像"))
        self.pushButton_3.setText(_translate("Form", "SFM"))
        self.pushButton_4.setText(_translate("Form", "PMVS"))
        self.pushButton_5.setText(_translate("Form", "点云构建"))
        self.groupBox.setTitle(_translate("Form", "信息"))

    def showInfo(self, type, strInfo):
        if type == "3D":
            self.textEdit.append(strInfo)
        else:
            self.infoEmit.emit(type, strInfo)

    # def async(f):
    #     def wrapper(*args, **kwargs):
    #         thr = QtCore.QThread(target=f, args=args, kwargs=kwargs)
    #         thr.start()
    #     return wrapper

    def actionCallVisualSFM(self):
        self.callModule.setPara({"code": 100})
        self.callModule.start()
        self.showInfo("3D", " -[SFM] 已启动 VisualSFM 三维重建模块")

    def actionCallMeshLab(self):
        self.callModule.setPara({"code": 101})
        self.callModule.start()
        self.showInfo("3D", " -[SFM] 已启动 MeshLab 点云重建模型-纹理贴图处理模块")
