# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeWight.ui'
#
<<<<<<< HEAD
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
=======
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
>>>>>>> 0367410d2d6020c98991c05162feaad2ccc434fb


from PyQt5 import QtCore, QtGui, QtWidgets


<<<<<<< HEAD
class Ui_Form(QtCore.QObject):
    imageEmit = QtCore.pyqtSignal()
    videoEmit = QtCore.pyqtSignal()
    modelEmit = QtCore.pyqtSignal()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1143, 682)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
=======
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(958, 532)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
>>>>>>> 0367410d2d6020c98991c05162feaad2ccc434fb
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLinkButton_2.sizePolicy().hasHeightForWidth())
        self.commandLinkButton_2.setSizePolicy(sizePolicy)
        self.commandLinkButton_2.setMinimumSize(QtCore.QSize(0, 150))
<<<<<<< HEAD
        self.commandLinkButton_2.setMaximumSize(QtCore.QSize(16777215, 400))
        self.commandLinkButton_2.setDefault(False)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.verticalLayout.addWidget(self.commandLinkButton_2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.button_image = QtWidgets.QPushButton(self.groupBox)
        self.button_image.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.button_image.setFont(font)
        self.button_image.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_image.setMouseTracking(False)
        self.button_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_image.setStyleSheet("color: rgb(255, 124, 16);")
        self.button_image.setCheckable(False)
        self.button_image.setAutoRepeat(False)
        self.button_image.setAutoExclusive(False)
        self.button_image.setAutoDefault(False)
        self.button_image.setDefault(False)
        self.button_image.setFlat(True)
        self.button_image.setObjectName("button_image")
        self.verticalLayout.addWidget(self.button_image)
        self.button_video = QtWidgets.QPushButton(self.groupBox)
        self.button_video.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(10)
        font.setUnderline(True)
        self.button_video.setFont(font)
        self.button_video.setStyleSheet("color: rgb(23, 174, 255);")
        self.button_video.setAutoExclusive(False)
        self.button_video.setAutoDefault(True)
        self.button_video.setDefault(False)
        self.button_video.setFlat(True)
        self.button_video.setObjectName("button_video")
        self.verticalLayout.addWidget(self.button_video)
        self.button_modelChange = QtWidgets.QPushButton(self.groupBox)
        self.button_modelChange.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.button_modelChange.setFont(font)
        self.button_modelChange.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_modelChange.setMouseTracking(False)
        self.button_modelChange.setStyleSheet("color: rgb(255, 124, 16);")
        self.button_modelChange.setCheckable(False)
        self.button_modelChange.setAutoRepeat(False)
        self.button_modelChange.setAutoExclusive(False)
        self.button_modelChange.setAutoDefault(False)
        self.button_modelChange.setDefault(False)
        self.button_modelChange.setFlat(True)
        self.button_modelChange.setObjectName("button_modelChange")
        self.verticalLayout.addWidget(self.button_modelChange)
        spacerItem1 = QtWidgets.QSpacerItem(258, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
=======
        self.commandLinkButton_2.setDefault(False)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.horizontalLayout.addWidget(self.commandLinkButton_2)
>>>>>>> 0367410d2d6020c98991c05162feaad2ccc434fb
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(650, 250))
        self.label.setText("")
<<<<<<< HEAD
        self.label.setPixmap(QtGui.QPixmap("./source/icon/VPL.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        self.button_image.clicked.connect(self.imageEmit.emit)
        self.button_video.clicked.connect(self.videoEmit.emit)
        self.button_modelChange.clicked.connect(self.modelEmit.emit)
=======
        self.label.setPixmap(QtGui.QPixmap("./source/icon/EMACS.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
>>>>>>> 0367410d2d6020c98991c05162feaad2ccc434fb
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
<<<<<<< HEAD
        self.commandLinkButton_2.setText(_translate("Form", "欢迎使用交通场景智能监控综合系统(ITSMS)"))
        self.commandLinkButton_2.setDescription(_translate("Form", "1.请在菜单栏选择相应的功能完成指定操作；\n"
                                                                   "2.该软件为工程测量相关计算的集成；\n"
                                                                   "3.详细使用帮助，请查看文档。"))
        self.label_2.setText(_translate("Form", "       功能引导："))
        self.button_image.setText(_translate("Form", "图像目标检测与流量统计"))
        self.button_video.setText(_translate("Form", "监控视频超速车辆检测"))
        self.button_modelChange.setText(_translate("Form", "自定义模型训练"))
=======
        self.commandLinkButton_2.setText(_translate("Form", "欢迎使用GNSS导航定位与测量综合系统"))
        self.commandLinkButton_2.setDescription(_translate("Form", "1.请在菜单栏选择相应的功能完成指定操作；\n"
"2.该软件为GNSS测量等相关计算的集成；\n"
"3.详细使用帮助，请查看文档。"))
>>>>>>> 0367410d2d6020c98991c05162feaad2ccc434fb
