# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowDS.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
import time

from PyQt5 import QtCore, QtGui, QtWidgets

from database.database import Database
from window import coorTranWight, coorTranOpenFileDiaog, welcomeWight
from window.tipDig import ActionWarnException


class Ui_mainWindow(object):
    wightStatus = 0

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1241, 725)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./source/icon/icon_资料.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.verticalLayout_4.addWidget(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./source/icon/icon_流水线.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.tableWidget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./source/icon/icon_网络教育.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.tab_4)
        self.progressBar.setProperty("value", 40)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./source/icon/icon_混合式学习.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("./source/icon/icon_垃圾桶.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./source/icon/ethereum-mining.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon4, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1241, 26))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_C = QtWidgets.QMenu(self.menubar)
        self.menu_C.setObjectName("menu_C")
        self.menu_S = QtWidgets.QMenu(self.menubar)
        self.menu_S.setObjectName("menu_S")
        self.menu_V = QtWidgets.QMenu(self.menubar)
        self.menu_V.setObjectName("menu_V")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtWidgets.QDockWidget(mainWindow)
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.treeView = QtWidgets.QTreeView(self.groupBox)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionx = QtWidgets.QAction(mainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./source/icon/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionx.setIcon(icon5)
        self.actionx.setObjectName("actionx")
        self.actionx_2 = QtWidgets.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./source/icon/futuro_icons_547.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionx_2.setIcon(icon6)
        self.actionx_2.setObjectName("actionx_2")
        self.actions = QtWidgets.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./source/icon/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actions.setIcon(icon7)
        self.actions.setObjectName("actions")
        self.actionss = QtWidgets.QAction(mainWindow)
        self.actionss.setObjectName("actionss")
        self.actiond = QtWidgets.QAction(mainWindow)
        self.actiond.setObjectName("actiond")
        self.actions_2 = QtWidgets.QAction(mainWindow)
        self.actions_2.setObjectName("actions_2")
        self.actionsd = QtWidgets.QAction(mainWindow)
        self.actionsd.setObjectName("actionsd")
        self.actionsd_2 = QtWidgets.QAction(mainWindow)
        self.actionsd_2.setObjectName("actionsd_2")
        self.actiond_2 = QtWidgets.QAction(mainWindow)
        self.actiond_2.setObjectName("actiond_2")
        self.actionsd_3 = QtWidgets.QAction(mainWindow)
        self.actionsd_3.setObjectName("actionsd_3")
        self.actiondf = QtWidgets.QAction(mainWindow)
        self.actiondf.setObjectName("actiondf")
        self.actiond_3 = QtWidgets.QAction(mainWindow)
        self.actiond_3.setObjectName("actiond_3")
        self.actiond_4 = QtWidgets.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./source/icon/pc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiond_4.setIcon(icon8)
        self.actiond_4.setObjectName("actiond_4")
        self.actionf = QtWidgets.QAction(mainWindow)
        self.actionf.setObjectName("actionf")
        self.actiond_5 = QtWidgets.QAction(mainWindow)
        self.actiond_5.setObjectName("actiond_5")
        self.actions_3 = QtWidgets.QAction(mainWindow)
        self.actions_3.setObjectName("actions_3")
        self.action_O = QtWidgets.QAction(mainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./source/icon/报表统计.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_O.setIcon(icon9)
        self.action_O.setObjectName("action_O")
        self.actionb = QtWidgets.QAction(mainWindow)
        self.actionb.setObjectName("actionb")
        self.menu_F.addAction(self.actionx)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionx_2)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actions)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_O)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionss)
        self.menu_C.addAction(self.actiond)
        self.menu_C.addSeparator()
        self.menu_C.addAction(self.actions_2)
        self.menu_C.addSeparator()
        self.menu_C.addAction(self.actionsd)
        self.menu_C.addSeparator()
        self.menu_C.addAction(self.actionsd_2)
        self.menu_C.addSeparator()
        self.menu_C.addAction(self.actiond_2)
        self.menu_C.addSeparator()
        self.menu_C.addAction(self.actionsd_3)
        self.menu_C.addSeparator()
        self.menu_S.addAction(self.actiondf)
        self.menu_S.addAction(self.actiond_3)
        self.menu_S.addAction(self.actiond_4)
        self.menu_V.addAction(self.actionb)
        self.menu_H.addAction(self.actiond_5)
        self.menu_H.addAction(self.actions_3)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_C.menuAction())
        self.menubar.addAction(self.menu_S.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.menubar.addAction(self.menu_V.menuAction())
        self.toolBar.addAction(self.actionx)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actiond_4)
        self.toolBar.addAction(self.actionx_2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actions)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_O)
        self.toolBar.addSeparator()

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)

        self.welcomeWight_ui = welcomeWight.Ui_Form()
        self.welcomeWight_ui.setupUi(self.widget)
        self.welcomeWight()

        self.coorTranWight_ui = coorTranWight.Ui_Form()
        self.coorTranWight_ui.infoEmit.connect(self.displayInfo)

        self.dialog = QtWidgets.QDialog()
        self.dialogUi = coorTranOpenFileDiaog.Ui_Dialog()
        self.dialogUi.fileReadEmit.connect(self.setOpenFileInfo)
        self.dialogUi.infoEmit.connect(self.displayInfo)

        self.pushButton.clicked.connect(self.showPan)
        self.actiond.triggered.connect(self.coorTranQwight)
        self.actionx_2.triggered.connect(self.coorTranOpenFileDialog)
        self.actions_2.triggered.connect(self.welcomeWight)

        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "工程测量软件设计窗口初稿(*测试功能用)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "操作"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "New Column"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "New Row"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "New Column"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "New Column"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "监控"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainWindow", "点位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "其他"))
        self.menu_F.setTitle(_translate("mainWindow", "文件(&F)"))
        self.menu_C.setTitle(_translate("mainWindow", "功能选择(&C)"))
        self.menu_S.setTitle(_translate("mainWindow", "设置(&S)"))
        self.menu_V.setTitle(_translate("mainWindow", "版本(&V)"))
        self.menu_H.setTitle(_translate("mainWindow", "帮助(&H)"))
        self.dockWidget_2.setWindowTitle(_translate("mainWindow", "状态栏"))
        self.label_2.setText(_translate("mainWindow", "文件列表"))
        self.label.setText(_translate("mainWindow", "程序状态信息"))
        self.pushButton.setText(_translate("mainWindow", "状态监测"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionx.setText(_translate("mainWindow", "新建(&N)"))
        self.actionx_2.setText(_translate("mainWindow", "打开文件(&O)"))
        self.actions.setText(_translate("mainWindow", "保存文件(&S)"))
        self.actionss.setText(_translate("mainWindow", "退出系统(&Q)"))
        self.actiond.setText(_translate("mainWindow", "二维坐标变换(&T)"))
        self.actions_2.setText(_translate("mainWindow", "徕卡数字水准仪格式转换及输出(&P)"))
        self.actionsd.setText(_translate("mainWindow", "地面控制网平差(&D)"))
        self.actionsd_2.setText(_translate("mainWindow", "铁路曲线计算(&T)"))
        self.actiond_2.setText(_translate("mainWindow", "CPIII控制网平差(&C)"))
        self.actionsd_3.setText(_translate("mainWindow", "静态GNSS网平差(&G)"))
        self.actiondf.setText(_translate("mainWindow", "计算参数(&S)"))
        self.actiond_3.setText(_translate("mainWindow", "系统参数(&S)"))
        self.actiond_4.setText(_translate("mainWindow", "界面设置(&W)"))
        self.actionf.setText(_translate("mainWindow", "f"))
        self.actiond_5.setText(_translate("mainWindow", "在线帮助(&I)"))
        self.actions_3.setText(_translate("mainWindow", "本地文档(&)"))
        self.action_O.setText(_translate("mainWindow", "导出结果报告(&O)"))
        self.actionb.setText(_translate("mainWindow", "版本信息(&V)"))

    def displayInfo(self, type, strInfo):

        if type == "I":
            self.textEdit_2.append(strInfo)
        else:
            ActionWarnException(self.centralwidget).actionWarnException(type, strInfo)

    def showPan(self):
        """
        文件列表树
        :return:None
        """
        model = QtWidgets.QDirModel()
        self.treeView.setModel(model)

    def coorTranQwight(self):
        """
        坐标转换功能面板
        :return: None
        """
        _translate = QtCore.QCoreApplication.translate
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "坐标转换"))
        # 界面重构存储区域
        self.widget.deleteLater()
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.verticalLayout_4.addWidget(self.widget)
        self.coorTranWight_ui.setupUi(self.widget)

    def welcomeWight(self):
        """
        欢迎页面
        :return: None
        """
        _translate = QtCore.QCoreApplication.translate

        self.widget.deleteLater()
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.verticalLayout_4.addWidget(self.widget)
        self.welcomeWight_ui.setupUi(self.widget)

    def coorTranOpenFileDialog(self):
        """
        坐标文件打开对话框
        :return: None
        """
        _translate = QtCore.QCoreApplication.translate
        # 界面重构存储区域
        self.dialogUi.setupUi(self.dialog)
        self.dialog.show()

    def setOpenFileInfo(self, typeInt):
        """

        :param typeInt: 文件类型
        :return:
        """
        self.textEdit_2.append("导入文件....")
        self.textEdit_2.append("数据如下：")
        if typeInt == 0:
            self.textEdit_2.append("---【原始坐标文件】---")
            self.textEdit_2.append(str(Database.coorTranSourceData))
        else:
            self.textEdit_2.append("---【目标坐标文件】---")
            self.textEdit_2.append(str(Database.coorTranTargetData))
